# Site settings
title: "Muhammad Hassaan"
description: "Data Scientist | Kaggle Expert | AI, ML, Deep Learning, Predictive Modeling & Data Analytics"
author: "Muhammad Hassaan"
baseurl: "" # Leave blank for GitHub Pages
url: "https://iammuhammadhassaan.github.io" # Replace <your-username> with your GitHub username
github_username: "iammuhammadhassaan"

# Theme
theme: jekyll-theme-minimal # You can change this to any supported GitHub Pages theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation links
nav_links:
  - name: "Home"
    url: "/"
  - name: "About Me"
    url: "/about/"
  - name: "Portfolio"
    url: "/portfolio/"
  - name: "Blog"
    url: "/blog/"
  - name: "Contact"
    url: "/contact/"

# Social media links
social_links:
  - name: "GitHub"
    url: "https://github.com/iammuhammadhassaan"
  - name: "LinkedIn"
    url: "https://linkedin.com/in/iammuhammadhassaan"
  - name: "Kaggle"
    url: "https://www.kaggle.com/mhassaan1122"


